<?php

namespace Database\Seeders;

use App\Models\Peserta;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PesertaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nama = [
            "Prof. Dr. Nurhayati, M.Ag.",
            "Prof. Dr. H. Azhari Akmal Tarigan, M.Ag.",
            "Dr. Abrar M. Dawud Faza, S.Fil., M.A.",
            "Prof. Dr. Katimin, M.A.",
            "Prof. Dr. H. Muzakkir, M.Ag.",
            "Drs. H. Ibnu Sadan, M.Pd.",
            "Dr. Tohar Bayoangin, M.Ag",
            "Darwis, SE., M.Si",
            "Hafni Hafsah, S.Ag., M.A.",
            "Abdul Basid Lubis, S.Pd.I., M.Pd",
            "Muhammad Akhir Nasution, S.Pd.i",
            "Rahmat Daim Harahap, S.E., M.Ak",
            "Prof. Dr. Pagar, M.Ag.",
            "Hotbin Hasugian, S.E., M.Si",
            "Prof. Dr. Amiruddin Siahaan, M.Pd ",
            "Prof. Dr. Tien Rafida, M.Hum.",
            "Dr. Syafruddin Syam, M.Ag.",
            "Dr. Maraimbang, M.A.",
            "Prof. Dr. Hasan Sazali, M.Ag",
            "Prof. Dr. Muhammad Syukri Albani Nasution, S.H.I., M.A",
            "Dr. Zulham, S.H.I., M.Hum",
            "Dr. Hj. Nursapia Harahap, M.A.",
            "Prof. Dr. Mesiono, M.Pd.",
            "Prof. Dr. Nurussakinah Daulay, M.Psi",
            "Dr. Muhammad Yafiz, M.Ag",
            "Dr. Nispul Khoiri, M.Ag.",
            "Muhammad Ikhsan, S.T., M.Kom",
            "Prof. Dr. Watni Marpaung, S.H.I., M.A",
            "Prof. Dr. Ansari, M.A",
            "Hildayati Raudah Hutasoit, S.Sos",
            "Idris Siregar, M.Ag",
            "Prof. Dr. Candra Wijaya, M.Pd",
            "Dr. Sugeng Wanto, M.Ag.",
            "Dr. Elly Warnisyah Harahap, M.Ag.",
            "Dr. Hasnun Jauhari Ritonga, S.Ag., M.A",
            "Dr. Isnaini Harahap, M.Ag.",
            "Dr. M. Ridwan, M.Ag.",
            "Dr. Hasrat Efendi Samosir, M.A.",
            "Dra. Retno Sayekti, M.Lis.",
            "Dr. Muhammad Dalimunte, S.Ag., S.S. M.Hum",
            "Dr. Fatimah Zahara, M.A.",
            "Dr. Muhammad Nuh Siregar, S.Ag., M.A",
            "Dr. Elfi Yanti Ritonga, M.A.",
            "Dr. Fauzi Arif Lubis, M.A.",
            "Dr.Hj. Nurhanifah, M.A.",
            "Dr. Asnil Aidah Ritonga, M.A.",
            "Dr. Abdul Karim Batubara, S.Sos., M.A",
            "Dr. Nurul Huda Prasetiya, M.A.",
            "Dr. Muhammad Rifai, S.Ag., M.Pd",
            "Dr. Uqbatul Khoir Rambe, M.A.",
            "Dr. Anang Anas Azhar, M.A",
            "Dr. Marliyah, M.Ag.",
            "Prof. Dr. Achyar Zein, M.Ag.",
            "Dr. Irwansyah, M.H.",
            "M. Yoserizal Saragih, S.Ag., M.I.Kom.",
            "Prof. Dr. Abdullah, M.Si.",
            "Dr. Salamuddin, S.Ag, MA",
            "Dr. Junaidi, S.Pd.I., M.Si.",
            "Dr. Syawaluddin Nasution, M.Ag.",
            "Fauziah Nasution, M.Psi.",
            "Reni Ria Armayani Hasibuan, M.E.I.",
            "Dr. Chuzaimah Batubara, M.A.",
            "Khairina Tambunan, M.E.I.",
            "Prof. Dr. Mustapa Khamal Rokan, S.H.I., M.H.",
            "Dr. Muhammad Irwan Padli Nasution, S.T., M.M.",
            "Dr. Muhammad Fadhli, M.Pd.",
            "Raissa Amanda Putri, S.Kom., M.TI.",
            "Dr. Ryandi, M.Ud.",
            "Putra Apriadi Siregar, M.Kes.",
            "Fitri Hayati, S.E., M.A.",
            "Dr. Mhd Furqon, S.Si., M.Com., Sc.",
            "Yunni Salma, S.Ag, M.M",
            "Amin Al Jawi, S.E.I., M.A.",
            "Abdul Jousef Sitepu, S.Ag.",
            "Dr. Hera Herviana, M.Kom.",
            "Asriani, S.Ag.",
            "Bambang Lesmono, S.E., M.E.",
            "Asmahani Mukhtar Ghaffar, S.E., M.Si.",
            "Dr. Rafnitul Hasanah Harahap, S.Ag., M.A.",
            "Nining Nurbaity, S.Kom., M.M.",
            "Nuraini Harahap, S.Ps,i",
            "Subhan Dawawi, S. Pd.I., M.M.",
            "Mimi Sahira, M.Ap.",
            "Munawir, SE.",
            "Muhammad Ikhbal Syaiful, S.H.I, M.H.",
            "Cahaya Br Ginting, S.Pd.I.",
            "Mizanuddin, S.Ag., M.A.  ",
            "Arif Rahman, S.E.",
            "Nur Arina Yunita Angkat, SE.I.",
            "Sonyamelinda Nasution, SE.",
            "Wirdayanti, SE",
            "Muhammad Said, S.H.",
            "Hasnan Habib Harahap, S.E",
            "Taufiq Muharrada Nasution, SE.",
            "Irwanto, SE.",
            "Ayatollah Muhammad Ramadhani, S.E.",
            "Budiono Silalahi, SE.",
            "Salman Hafiz, S.E.",
            "Mardi, S.E.",
            "Dwi Sandhi Romadhon, SE.",
            "Nur Faznita Elmi, S.Akun.",
            "Heprina Hera Rezeki, S.Akun.",
            "Hj. Ernawati, SE, M.AP.",
            "Sri Cahyanti, S. Sos. I.",
            "Indri Octa Miransyah, S.Pd.",
            "Ibnu Rusydi, S.Kom., M.Kom.",
            "Akhyar Aslam Sipahutar, S.T.",
            "Edi Syahputra, S.E.I.",
            "Lailan Safinah Harahap, M.Kom.",
            "Rezkia Amelia, M.A, M.Pd.",
            "Muhammad Arief, S.H.",
            "Muhammad Yusuf Ramadhan, S.Kom.",
            "dr. Rachmah Ubat Harahap.",
            "Syahroini A.M.K.",
            "Emigawati, SE,",
            "M. Ilham Lutfhi.",
            "Abdurrahman Lubis.",
            "Asrul.",
            "Ali Mukhtar Siregar.",
            "Edy Sanjaya.",
            "Muhammad Nasri.",
            "Affandi Indra Sani",
            "Musa Pulungan.",
            "Rahmat Subandri.",
            "Kari Kiraman"
        ];

        $role = [
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Panitia",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta",
            "Peserta"
        ];


        $golongan =     [
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "III",
            "IV",
            "IV",
            "III",
            "III",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "III",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "IV",
            "III",
            "IV",
            "IV",
            "IV",
            "III",
            "III",
            "IV",
            "III",
            "IV",
            "IV",
            "IV",
            "III",
            "III",
            "III",
            "IV",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III",
            "III"
        ];

        for($i = 0; $i < count($nama); $i++){
            Peserta::create([
                'role' => $role[$i],
                'nama' => $nama[$i],
                'instansi' => 'UIN Sumatera Utara Medan',
                'golongan' => $golongan[$i],
            ]);
        }
    }
}
